services:
  workspace:
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/workspace:cached
    command: sleep infinity
  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "secret"
  prism:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /tmp/api.yaml"
    volumes:
      - ./api/openapi.yml:/tmp/api.yaml:ro
    ports:
      - "4010:4010"
volumes:
  db-store:
